apiVersion: apps/v1
kind: Deployment
metadata:
  name: peterengland-website
  labels:
    app: peterengland-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peterengland-website
  template:
    metadata:
      labels:
        app: peterengland-website
    spec:
      containers:
        - name: peterengland-website
          image: mounikasannaiela/game_app:ee59c450
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
